version: "3"

vars:
  PYTHON: python
  UV: uv
  APP: celine.rec_registry.main:app
  HOST: 0.0.0.0
  PORT: 8000

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies using uv
    cmds:
      - "{{.UV}} sync"

  format:
    desc: Format code (if ruff is added later). Placeholder.
    cmds:
      - echo "No formatter configured. Add ruff/black if desired."

  run:
    desc: Run the API locally (reload)
    cmds:
      - "{{.UV}} run uvicorn {{.APP}} --host {{.HOST}} --port {{.PORT}} --reload"

  test:
    desc: Run tests (if added later)
    cmds:
      - echo "No tests configured yet."

  db:up:
    desc: Start PostgreSQL via docker compose
    cmds:
      - docker compose up -d db

  db:down:
    desc: Stop PostgreSQL
    cmds:
      - docker compose down

  db:reset:
    desc: Drop and recreate Postgres volume (DANGEROUS)
    cmds:
      - docker compose down -v
      - docker compose up -d db

  db:migrate:
    desc: Apply Alembic migrations (upgrade head)
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
    deps: [install]
    cmds:
      - "{{.UV}} run alembic upgrade head"

  db:revision:
    desc: "Create a new Alembic revision (autogenerate). Usage: task db:revision -- -m <message>"
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
    deps: [install]
    cmds:
      - "{{.UV}} run alembic revision --autogenerate {{.CLI_ARGS}}"

  import:community:
    desc: "Import a community YAML (REPLACE mode). Usage: task import:community -- --file path.yaml"
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
    deps: [install]
    cmds:
      - "{{.UV}} run celine-rec-registry import community {{.CLI_ARGS}}"

  dev:up:
    desc: Start dev stack (db + api)
    cmds:
      - docker compose up -d --build

  dev:logs:
    desc: Tail API logs
    cmds:
      - docker compose logs -f api

  dev:ps:
    desc: Show compose services
    cmds:
      - docker compose ps
