version: "3"

vars:
  EXEC: docker compose exec api uv run
  APP: celine.rec_registry.main:app

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  run:
    desc: Start services
    cmds:
      - docker compose up -d

  db:reset:
    deps: [run]
    desc: Drop and recreate Postgres volume (DANGEROUS)
    cmds:
      - docker compose down -v
      - docker compose up -d db

  db:migrate:
    deps: [run]
    desc: Apply Alembic migrations (upgrade head)
    cmds:
      - "{{.EXEC}} alembic upgrade head"

  db:revision:
    deps: [run]
    desc: "Create a new Alembic revision (autogenerate). Usage: task db:revision -- -m <message>"
    cmds:
      - "{{.EXEC}} alembic revision --autogenerate {{.CLI_ARGS}}"

  import:community:
    deps: [run]
    desc: "Import a community YAML (REPLACE mode). Usage: task import:community -- --file path.yaml"
    cmds:
      - "{{.EXEC}} celine-rec-registry import community {{.CLI_ARGS}}"

  import:community:example:
    deps: [run]
    desc: "Import community example"
    cmds:
      - task import:community -- --file rec-example.yaml
